### ISSUE TITLE
`tea` No such file or directory

### ISSUE THREAD

**Issue by mxcl** [teaxyz/infuser#5]
![Screen Shot 2022-09-24 at 12 58 35 PM](https://user-images.githubusercontent.com/58962/192109946-81dd0672-5067-47d2-b9a7-e098bb5214ff.png)

There should be:

* `/opt/tea.xyz/v*`
* `/opt/tea.xyz/v0.x.y`
* `/opt/tea.xyz/v0.x`
* `/opt/tea.xyz/v0`

where x and y are the actual version numbers ofc

**Comment by mxcl** [comment]
oh and the `tea` that is there doesn't actually work because we need to replace the `version` line like we do in tea’s package.yml

**Comment by mxcl** [comment]
maybe we should build tea with tea in stage2?

**Comment by jhheider** [comment]
Could be. Which version of tea is there? The nightlies take 6 hours and blips in http requests can kill the whole thing, so it can get stale slightly easily.

**Comment by jhheider** [comment]
Adding to stage2 has a super high likelihood of working, since all the linking logic will run. Probably add deno.land too, despite the build time bloat.

**Comment by mxcl** [comment]
> Which version of tea is there? 

It builds whatever version is in `cli` when you build the docker image.

So, I hope both `cli` and `pantry` are being updated to the latest versions for the nightlies?

**Comment by jhheider** [comment]
Yup. The problem was version not being captured in stage 0 (I assume because main was between tags) so the directory was /opt/tea.xyz/v which the repair.ts wasn't linking. Solution was to actually build tea.xyz in Dockerfile.
